### ISSUE TITLE
Web failed to start after update tork to 0.1.88

### ISSUE THREAD

**Issue by ppcololo** [runabol/tork-web#19]
Hello
I updated tork to 0.1.88 and also updated tork-web to latest
Now web failed to start with this error:

```
> tork-web@0.1.12 start
> dotenv -c -- next start

   ▲ Next.js 14.0.4
   - Local:        http://localhost:8100

 ✓ Ready in 1294ms
Error: Failed to fetch data
    at g (/app/.next/server/app/jobs/page.js:1:6181)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async h (/app/.next/server/app/jobs/page.js:1:2460)
[Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
  digest: '251103190'
}
```

during tork start I can see this:
```
2:23PM INF Config loaded from config.toml

 _______  _______  ______    ___   _
|       ||       ||    _ |  |   | | |
|_     _||   _   ||   | ||  |   |_| |
  |   |  |  | |  ||   |_||_ |      _|
  |   |  |  |_|  ||    __  ||     |_
  |   |  |       ||   |  | ||    _  |
  |___|  |_______||___|  |_||___| |_|

 0.1.88 (d252e0e)

error when trying to create db schema: pq: relation "nodes" already exists
2:23PM INF Config loaded from config.toml
```

**Comment by runabol** [comment]
are you trying to run the db migration?

**Comment by ppcololo** [comment]
yes - tork coordinator start with `tork migration || tork run coordinator`

**Comment by runabol** [comment]
migrations only work on a blank db at the moment. You'll either have to add missing schema parts manually or clear the db and let Tork initialize it.

**Comment by ppcololo** [comment]
yeah, already did it manually

I saved commands I applied to postgres, maybe someone will need this after upgrade to 0.1.88 :)

```
ALTER TABLE jobs ADD secrets jsonb;
ALTER TABLE jobs ADD tags text[] not null default '{}';
ALTER TABLE jobs ADD created_by varchar(32) references users(id);
ALTER TABLE jobs ADD delete_at timestamp;
ALTER TABLE tasks ADD priority int;
ALTER TABLE tasks ADD workdir varchar(256);

CREATE TABLE users (
    id          varchar(32)  not null primary key,
    name        varchar(64)  not null,
    username_   varchar(64)  not null unique,
    password_   varchar(256) not null,
    created_at  timestamp    not null,
    is_disabled boolean      not null default false
);

insert into users (id,name,username_,password_,created_at,is_disabled) (SELECT REPLACE(gen_random_uuid()::text, '-', ''),'Guest','guest','',current_timestamp,true);

CREATE TABLE roles (
    id          varchar(32)  not null primary key,
    name        varchar(64)  not null,
    slug        varchar(64)  not null unique,
    created_at  timestamp    not null
);

CREATE UNIQUE INDEX idx_roles_slug ON roles (slug);

insert into roles (id,name,slug,created_at) (SELECT REPLACE(gen_random_uuid()::text, '-', ''),'Public','public',current_timestamp);

CREATE TABLE users_roles (
    id         varchar(32) not null primary key,
    user_id    varchar(32) not null references users(id),
    role_id    varchar(32) not null references roles(id),
    created_at timestamp   not null
);

CREATE UNIQUE INDEX idx_users_roles_uniq ON users_roles (user_id,role_id);

CREATE TABLE jobs_perms (
    id      varchar(32) not null primary key,
    job_id  varchar(32) not null references jobs(id),
    user_id varchar(32)          references users(id),
    role_id varchar(32)          references roles(id)
);

CREATE INDEX jobs_perms_job_id_idx ON jobs_perms (job_id);
CREATE INDEX jobs_perms_user_role_idx ON jobs_perms (user_id,role_id);
CREATE INDEX idx_jobs_created_at ON jobs (created_at);
```

and after all it needs:
```
update tasks set workdir = '';
update tasks set priority = 1;
update jobs set created_by = 'd514c7931d08410e96ddb1ce79de0c42'; <-- user ID from users
```

**Comment by runabol** [comment]
Thanks for putting this together!
